"""
Forge the Gloamstead sanctuary audio set, deterministically, from nothing but the standard library.

WHY THIS EXISTS
    Content/ contains zero sound assets -- not one wave, cue or MetaSound anywhere in the project.
    The game is not silent: Source/Gloamstead/Audio/GloamsteadSanctuarySynth.cpp generates a bed
    sample-by-sample, and GloamsteadSoundscapeSubsystem.cpp drives it per phase. But a runtime synth
    is the half that can ship without an artist; it is not audio *content*, it cannot be auditioned
    in the editor, it cannot be routed through a sound class, and it cannot be handed to a mixer.
    This script authors the content half -- the beds and the three moments the design says the
    player must hear -- with the same "no artist, no DAW, no dependency" constraint the texture lane
    already answered for surfaces.

WHY PURE STDLIB
    No numpy, no scipy, no soundfile. Sine tables, one-pole filters and an xorshift noise source are
    written out by hand and the RIFF is emitted through `wave`. Same reasoning as
    procedural/textures/forge_sanctuary_textures.py: a content pipeline that needs a bespoke
    environment is a content pipeline that stops working. Anything that can run the engine can run
    this.

WHY DETERMINISTIC
    Every random number here comes from SEED below through a hand-rolled xorshift, seeded by an
    explicit integer/string key -- never from `random`, whose stream is a stdlib implementation
    detail, and never from time or dict order. Two runs on the same machine produce byte-identical
    WAVs, which is what makes the generated .uasset reviewable: a diff in Content/ means somebody
    changed the *recipe*, not that the generator rolled different dice.

    Honest boundary: the only cross-machine dependency is libm's `math.sin`, which is not
    bit-specified by the C standard. The determinism claim this script prints is the one that
    matters for review -- same machine, same interpreter, byte-identical output -- and is what the
    two-directory re-run check in the task actually proves.

WHY THE LOOPS CANNOT CLICK
    Not by crossfading. A crossfade hides a seam; it does not remove one, and it smears the tail of
    the loop into its own head. Instead every looping file is built to be *mathematically periodic*
    over its exact sample length N:

      * Every pitched partial and every LFO is snapped to an integer bin k, meaning exactly k whole
        cycles fit in N samples. It is generated by walking a shared table of sin(2*pi*j/N) with
        stride k, so sample N is by construction sample 0.
      * Every noise layer is filtered *circularly*: the filter state is primed on the tail of the
        buffer for at least 24 time constants before the real pass begins, so the state at sample N
        equals the state at sample 0 to ~1e-10 -- five orders of magnitude below a 16-bit LSB.
      * Every pointwise shaping function (gates, ramps, mixes) preserves periodicity trivially.

    So x[N] == x[0] by construction, and the loop point is not a special sample. The seam audit at
    the bottom of this file is the check on that claim, not the mechanism behind it: it compares the
    wrap-around step against the distribution of the file's own interior steps and fails loudly if
    the wrap is an outlier.

WHY THIS MATERIAL
    docs/art/04_art_direction.md: "mournful, sacred, weathered, and lonely", "small warmth against
    vast coldness", "Warmth must be earned through restoration", and -- read across from the texture
    rules -- "avoid high-frequency noise everywhere", "background decay should be quieter than
    meaningful structures". So: sparse, low, slow, hollow. Bare fifths rather than triads, because a
    fifth sounds like a place and a triad sounds like a feeling. No stingers, no swells that resolve,
    no reverb tail pretending to be a cathedral.

    The pitches are not invented here. They are lifted from
    UGloamsteadSoundscapeSubsystem::VoicingFor -- Day C3 130.81, Dusk A2 110, Night D2 73.42,
    Dawn D3 146.83 -- and the two struck tones from the same file's Strike() calls (Heart G3 196,
    Dawn D5 587.33). The recorded beds and the runtime synth therefore agree on the sanctuary's
    key instead of beating against each other when both are audible.

USAGE
    python forge_sanctuary_audio.py <output-directory>

    Writes seven 16-bit PCM mono 48 kHz WAVs and prints, per file, the duration, peak, RMS, DC
    offset, loop-seam audit and SHA-256.

    The companion is import_sanctuary_audio.py, which reads this directory from GLOAM_AUDIO_WAV_DIR.
"""

import hashlib
import math
import os
import sys
import wave
from array import array

# ----------------------------------------------------------------------------------------------
# Determinism
# ----------------------------------------------------------------------------------------------

# The single root of every random number in this file. Change it and the whole set changes; leave it
# alone and the set is reproducible forever.
SEED = 0x67104D  # "gloam" -- the same root the texture forge uses, for the same reason

SR = 48000  # the project's mixer runs at 48 kHz; resampling on import is a quality loss for free

# Authoring peak. Every file is normalised to the same peak and the mix decides loudness downstream:
# a bed baked quiet cannot be made loud without noise, but a bed baked at a known peak can be made
# any level at all with a volume multiplier. -6 dBFS leaves 6 dB of headroom for the runtime synth
# to sit underneath without the sum clipping.
TARGET_PEAK_DBFS = -6.0

INT16_MAX = 32767
FULL_SCALE = 32768.0


def _int_of(k):
    """Stable integer for an arbitrary key -- ints, strings, and tuples of those."""
    if isinstance(k, str):
        v = 0
        for ch in k:
            v = ((v * 131) + ord(ch)) & 0xFFFFFFFF
        return v
    if isinstance(k, (tuple, list)):
        v = 0
        for sub in k:
            v = ((v * 131) + _int_of(sub)) & 0xFFFFFFFF
        return v
    return int(k) & 0xFFFFFFFF


def _seed_for(key):
    h = (SEED ^ _int_of(key)) & 0xFFFFFFFF
    # xorshift32 has one fixed point: zero. Anything else would be an unseeded silent failure.
    return h if h else 0x9E3779B9


def white_noise(n, key):
    """`n` samples of uniform white noise in [-1, 1), from a hand-rolled xorshift32.

    Not random.Random: this must not depend on the behaviour of a stdlib PRNG across interpreter
    versions, which is the same argument the texture forge makes for its own mixer.
    """
    state = _seed_for(key)
    out = [0.0] * n
    for i in range(n):
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= state >> 17
        state ^= (state << 5) & 0xFFFFFFFF
        out[i] = (state / 2147483648.0) - 1.0
    return out


# ----------------------------------------------------------------------------------------------
# Exactly-periodic oscillators
# ----------------------------------------------------------------------------------------------

_TABLES = {}


def sine_table(n):
    """sin(2*pi*j/n) for j in [0, n). One table serves every partial of every file of length n."""
    t = _TABLES.get(n)
    if t is None:
        two_pi_over_n = (2.0 * math.pi) / n
        t = [math.sin(two_pi_over_n * j) for j in range(n)]
        _TABLES[n] = t
    return t


def bin_for(hz, n):
    """Nearest integer number of whole cycles of `hz` that fits in `n` samples.

    Bin resolution is SR/n -- 0.05 Hz for a 20-second loop -- so the snap is inaudible (a 0.02%
    detune at worst, far under the ~0.5% just-noticeable difference) and it is the entire reason the
    loop closes on the sample.
    """
    k = int(round(hz * n / float(SR)))
    if k < 1:
        k = 1
    if k >= n // 2:
        raise ValueError("frequency %r is at or above Nyquist for n=%d" % (hz, n))
    return k


def osc(n, hz, phase=0.0):
    """A sine of `hz` snapped to a bin, exactly periodic over n samples. `phase` is in turns.

    Generated by tiling: walking the table with stride k revisits its start after n/gcd(k, n)
    samples, so only that many values are ever computed. It is a large speedup on a 960k-sample
    buffer and, more importantly, it makes the periodicity structural rather than incidental.
    """
    table = sine_table(n)
    k = bin_for(hz, n)
    g = math.gcd(k, n)
    period = n // g
    idx = int(round(phase * n)) % n
    vals = [0.0] * period
    for i in range(period):
        vals[i] = table[idx]
        idx += k
        if idx >= n:
            idx -= n
    return vals * g if g > 1 else vals


def actual_hz(hz, n):
    """The frequency `osc` will really produce, after the bin snap. Printed, not assumed."""
    return bin_for(hz, n) * SR / float(n)


# ----------------------------------------------------------------------------------------------
# Filters
# ----------------------------------------------------------------------------------------------

def _pole(cutoff_hz):
    a = math.exp(-2.0 * math.pi * cutoff_hz / SR)
    # A pole of exactly 1.0 is an integrator, which on noise is a random walk to +/-inf. A pole of
    # exactly 0.0 is a no-op. Neither is ever what a cutoff was meant to express.
    if not (0.0 < a < 1.0):
        raise ValueError("cutoff %r Hz produced a degenerate pole %r" % (cutoff_hz, a))
    return a


PRIME_TIME_CONSTANTS = 24  # exp(-24) ~ 3.8e-11, against an int16 LSB of 3.05e-5


def circular_lowpass(x, cutoff_hz):
    """One-pole lowpass run as if `x` were an infinite loop of itself.

    The state is primed on the tail of the buffer for PRIME_TIME_CONSTANTS time constants before the
    output pass starts, so the state entering sample 0 is the state leaving sample n-1 to within
    ~1e-10. That is what keeps a filtered noise bed periodic; a filter started from zero puts a
    settling transient at the head of every loop, which is exactly the click the brief forbids.
    """
    a = _pole(cutoff_hz)
    b = 1.0 - a
    n = len(x)
    prime = min(n, int(PRIME_TIME_CONSTANTS / (1.0 - a)) + 1)
    y = 0.0
    for i in range(n - prime, n):
        y = b * x[i] + a * y
    out = [0.0] * n
    for i in range(n):
        y = b * x[i] + a * y
        out[i] = y
    return out


def circular_highpass(x, cutoff_hz):
    """Complement of the circular lowpass. Periodic for the same reason, and DC-free by definition."""
    lp = circular_lowpass(x, cutoff_hz)
    return [u - v for u, v in zip(x, lp)]


def lowpass(x, cutoff_hz, state=0.0):
    """Plain forward one-pole, for one-shots -- where starting from silence is correct, not a bug."""
    a = _pole(cutoff_hz)
    b = 1.0 - a
    y = state
    out = [0.0] * len(x)
    for i, v in enumerate(x):
        y = b * v + a * y
        out[i] = y
    return out


def highpass(x, cutoff_hz):
    lp = lowpass(x, cutoff_hz)
    return [u - v for u, v in zip(x, lp)]


def sweeping_lowpass(x, hz_start, hz_end, shape=2.0):
    """One-pole lowpass whose cutoff falls from hz_start to hz_end across the buffer.

    This is the whole identity of SFX_Threat_Near: a body of noise whose brightness collapses is
    heard as something close and physical settling, where a fixed filter is heard as a hiss.
    """
    n = len(x)
    out = [0.0] * n
    y = 0.0
    inv = 1.0 / max(n - 1, 1)
    for i, v in enumerate(x):
        t = (i * inv) ** shape
        a = _pole(hz_start + (hz_end - hz_start) * t)
        y = (1.0 - a) * v + a * y
        out[i] = y
    return out


# ----------------------------------------------------------------------------------------------
# Shaping
# ----------------------------------------------------------------------------------------------

def smoothstep(t):
    if t <= 0.0:
        return 0.0
    if t >= 1.0:
        return 1.0
    return t * t * (3.0 - 2.0 * t)


def mix_into(dst, src, gain):
    for i, v in enumerate(src):
        dst[i] += v * gain
    return dst


def multiply(a, b):
    return [u * v for u, v in zip(a, b)]


def unipolar(sig, floor=0.0):
    """Map a [-1, 1] oscillator to [floor, 1] -- an amplitude, not a waveform."""
    span = 1.0 - floor
    return [floor + span * (0.5 + 0.5 * v) for v in sig]


def gate(sig, threshold, softness):
    """Pointwise soft gate. Turns a smooth envelope into a sparse, gusting one.

    Pointwise, so it cannot break periodicity -- that is why the sparseness is applied here rather
    than by windowing the noise, which would.
    """
    out = [0.0] * len(sig)
    for i, v in enumerate(sig):
        out[i] = smoothstep((v - threshold) / softness)
    return out


def slow_field(n, specs):
    """Sum of very-low-frequency sines, normalised to [0, 1]. The weather under an ambient bed.

    Several mutually irrational-ish rates so the bed never audibly repeats before the loop does,
    which is what stops a 20-second ambience from sounding like a 20-second ambience.
    """
    acc = [0.0] * n
    total = 0.0
    for hz, amp, phase in specs:
        mix_into(acc, osc(n, hz, phase), amp)
        total += amp
    inv = 0.5 / total
    return [0.5 + v * inv for v in acc]


# ----------------------------------------------------------------------------------------------
# Voices
# ----------------------------------------------------------------------------------------------

def drone(n, root_hz, partials, key):
    """Additive bed. `partials` are (ratio, amplitude, breath_hz, breath_depth).

    Each partial breathes at its own slow rate, so the chord's internal balance drifts and the
    listener never hears a static stack. Every breath rate is bin-snapped like the partial itself.
    """
    out = [0.0] * n
    for index, (ratio, amp, breath_hz, breath_depth) in enumerate(partials):
        # Phase is deterministic per partial rather than all-zero: a stack of cosines that all start
        # at 1.0 sums to a transient at sample 0 that the loop then repeats once per pass.
        phase = ((_seed_for((key, "phase", index)) >> 8) & 0xFFFF) / 65536.0
        voice = osc(n, root_hz * ratio, phase)
        if breath_depth > 0.0:
            bphase = ((_seed_for((key, "breath", index)) >> 8) & 0xFFFF) / 65536.0
            env = unipolar(osc(n, breath_hz, bphase), 1.0 - 2.0 * breath_depth)
            voice = multiply(voice, env)
        mix_into(out, voice, amp)
    return out


def air(n, key, hp_hz, lp_hz, gate_spec, sparsity):
    """Band-limited noise with a sparse, gusting envelope. The room tone, not the drone.

    Two cascaded one-poles per side rather than one: a 6 dB/octave skirt leaves enough low rumble in
    a "high air" layer to muddy the drone, and enough top in a "floor" layer to hiss.
    """
    n_src = white_noise(n, (key, "src"))
    band = circular_highpass(circular_highpass(n_src, hp_hz), hp_hz)
    del n_src
    band = circular_lowpass(circular_lowpass(band, lp_hz), lp_hz)
    field = slow_field(n, gate_spec)
    env = gate(field, sparsity, 0.34)
    del field
    return multiply(band, env)


def struck(n, hz, partials, key, attack_s=0.004):
    """A struck tone: fast attack, per-partial exponential decay, slightly inharmonic.

    `partials` are (ratio, amplitude, decay_seconds). The ratios are deliberately NOT integers.
    A harmonic stack reads as an organ or a synth pad; a stone or a cast bell has stretched, drifting
    partials, and that inharmonicity is most of why a struck object sounds struck.
    """
    out = [0.0] * n
    attack = max(int(attack_s * SR), 1)
    two_pi_over_sr = (2.0 * math.pi) / SR
    for index, (ratio, amp, decay_s) in enumerate(partials):
        w = two_pi_over_sr * hz * ratio
        # exp() per sample is the honest way to write this and is a rounding-stable recurrence when
        # written as a constant multiply; at these lengths the cost is irrelevant.
        decay = math.exp(-6.907755 / max(decay_s * SR, 1.0))  # -60 dB over decay_s
        phase = ((_seed_for((key, index)) >> 8) & 0xFFFF) / 65536.0 * 2.0 * math.pi
        env = amp
        for i in range(n):
            a = env if i >= attack else env * (i / float(attack))
            out[i] += math.sin(phase + w * i) * a
            env *= decay
    return out


def fade_tail(sig, seconds):
    """Raised-cosine fade to exactly zero over the last `seconds`.

    A one-shot that stops mid-decay clicks on the trailing edge instead of the leading one, which is
    the failure mode nobody checks because the sound has already "finished" by then.
    """
    n = len(sig)
    m = min(int(seconds * SR), n)
    for i in range(m):
        t = i / float(m)
        sig[n - m + i] *= 0.5 * (1.0 + math.cos(math.pi * t))
    sig[n - 1] = 0.0
    return sig


# ----------------------------------------------------------------------------------------------
# The set
# ----------------------------------------------------------------------------------------------

AMBIENT_SECONDS = 20
AMBIENT_N = AMBIENT_SECONDS * SR


def amb_day():
    """Cold, quiet, high sparse air. Wounded but legible.

    Day is the phase the player is supposed to be able to think in, so the bed is mostly *space*:
    the drone sits low and almost still, and what moves is a thin band of air well above it. The
    fifth is present and the octave barely so -- open, hollow, and not company.
    """
    n = AMBIENT_N
    out = drone(n, 130.81, [           # C3, matching VoicingFor(Day)
        (0.5,  0.30, 0.05, 0.20),     # C2  -- floor under the room, felt more than heard
        (1.0,  1.00, 0.10, 0.26),     # C3  -- root
        (1.5,  0.42, 0.15, 0.30),     # G3  -- the bare fifth
        (2.0,  0.13, 0.25, 0.34),     # C4  -- brightness 0.55: open, but not lit
    ], "day")
    # High and sparse: 2.4-6.5 kHz, gated hard so it is mostly absent. The art direction's
    # "avoid high-frequency noise everywhere" applies to the ear as much as to the eye.
    mix_into(out, air(n, "day_air", 2400.0, 6500.0,
                      [(0.05, 1.00, 0.11), (0.10, 0.62, 0.47), (0.25, 0.38, 0.81)],
                      sparsity=0.52), 0.30)
    # A very quiet mid floor keeps the silence between gusts from sounding like a dropout.
    mix_into(out, air(n, "day_floor", 180.0, 900.0,
                      [(0.05, 1.0, 0.29), (0.15, 0.5, 0.63)], sparsity=0.14), 0.045)
    return out


def amb_dusk():
    """Interpretive tension; a low pulse entering.

    Dusk is the phase the design says should feel like a decision not yet finished, so this is the
    only bed with an interval that wants to resolve and does not: a minor sixth (F3 over A2) held
    against the fifth. The pulse is a swell on the sub, at the 0.28 Hz the runtime synth uses for
    this phase, shaped so it arrives rather than switches on.
    """
    n = AMBIENT_N
    out = drone(n, 110.0, [            # A2, matching VoicingFor(Dusk)
        (1.0,  1.00, 0.05, 0.22),     # A2
        (1.5,  0.34, 0.10, 0.28),     # E3  -- brightness 0.38: the fifth pulls back
        (1.587, 0.20, 0.20, 0.40),    # F3  -- the minor sixth. The unresolved one.
        (2.0,  0.075, 0.30, 0.36),    # A3
    ], "dusk")

    # The pulse: a sub sine gated by a slow raised swell rather than a sine, so it breathes in and
    # decays out instead of wobbling symmetrically. 0.30 Hz is the nearest bin to the synth's 0.28.
    sub = osc(n, 55.0, 0.13)
    swell = [smoothstep(v) ** 1.6 for v in unipolar(osc(n, 0.30, 0.0), 0.0)]
    mix_into(out, multiply(sub, swell), 0.36)
    del sub, swell

    mix_into(out, air(n, "dusk_air", 1500.0, 5200.0,
                      [(0.05, 1.0, 0.37), (0.15, 0.7, 0.71), (0.35, 0.4, 0.19)],
                      sparsity=0.44), 0.26)
    mix_into(out, air(n, "dusk_floor", 140.0, 1100.0,
                      [(0.05, 1.0, 0.53), (0.20, 0.6, 0.07)], sparsity=0.10), 0.075)
    return out


def amb_night():
    """Darker, lower fundamental, more noise floor.

    Night drops to D2 and closes the upper partials almost off (brightness 0.16). The tremolo is the
    one thing in the whole set that moves at a speed a listener can count -- 1.15 Hz, from the synth
    -- because the design's job at night is to make an empty room feel occupied before anything is
    visible. The noise floor is the loudest it gets anywhere, and it is low, not hissy: rot, not tape.
    """
    n = AMBIENT_N
    out = drone(n, 73.42, [            # D2, matching VoicingFor(Night)
        (0.5,  0.44, 0.05, 0.18),     # D1 -- sub. Below hearing on small speakers, and that is fine.
        (1.0,  1.00, 0.10, 0.24),     # D2
        (1.5,  0.155, 0.15, 0.30),    # A2 -- the fifth, nearly shut
        (2.0,  0.05, 0.20, 0.30),     # D3
        (2.995, 0.028, 0.30, 0.44),   # A3-ish, detuned. A partial that is very slightly wrong.
    ], "night")

    # Tremolo across the whole bed, not per-partial: the room dims and returns as one thing.
    trem = unipolar(osc(n, 1.15, 0.0), 0.72)   # 0.72..1.0, the same floor the synth uses
    out = multiply(out, trem)
    del trem

    mix_into(out, air(n, "night_floor", 90.0, 1400.0,
                      [(0.05, 1.0, 0.61), (0.15, 0.7, 0.23), (0.30, 0.45, 0.89)],
                      sparsity=0.06), 0.16)
    mix_into(out, air(n, "night_air", 2100.0, 5000.0,
                      [(0.05, 1.0, 0.31), (0.20, 0.6, 0.77)], sparsity=0.68), 0.085)
    return out


def amb_dawn():
    """Warmer, the noise floor receding.

    The only bed with a third in it. docs/art/04_art_direction.md: "Warmth must be earned through
    restoration" -- dawn is where it is earned, so this is the one place a major interval is allowed,
    and it is still quiet and still ends up back where it started. The high D5 shimmer is the same
    pitch the subsystem strikes on the dawn transition, so the struck tone lands inside the bed
    rather than on top of it.
    """
    n = AMBIENT_N
    out = drone(n, 146.83, [           # D3, matching VoicingFor(Dawn)
        (0.5,  0.26, 0.05, 0.16),     # D2
        (1.0,  1.00, 0.10, 0.20),     # D3
        (1.25, 0.30, 0.15, 0.26),     # F#3 -- the third. The warmth.
        (1.5,  0.46, 0.20, 0.24),     # A3
        (2.0,  0.20, 0.25, 0.30),     # D4  -- brightness 0.82: the most open voicing in the game
        (4.0,  0.045, 0.35, 0.52),    # D5  -- shimmer; the dawn strike's own pitch
    ], "dawn")
    # The floor recedes and returns once per loop rather than vanishing: a bed that fades to nothing
    # reads as a bug in-game, where the loop restarts under a player who is still standing there.
    recede = [0.30 + 0.70 * (1.0 - smoothstep(v)) for v in unipolar(osc(n, 0.05, 0.25), 0.0)]
    floor = air(n, "dawn_floor", 120.0, 1000.0,
                [(0.05, 1.0, 0.43), (0.20, 0.55, 0.11)], sparsity=0.20)
    mix_into(out, multiply(floor, recede), 0.055)
    del floor, recede
    mix_into(out, air(n, "dawn_air", 2800.0, 7500.0,
                      [(0.05, 1.0, 0.67), (0.15, 0.8, 0.13), (0.30, 0.4, 0.41)],
                      sparsity=0.40), 0.20)
    return out


def sfx_heart_warning():
    """A low struck tone with a long decay. This is the Heart speaking.

    G3 196 Hz, the exact pitch UGloamsteadSoundscapeSubsystem::HandleHeartWarning strikes. Stretched
    inharmonic partials over a sub octave, so it reads as a large stone object being struck once
    rather than as a notification. Under the bed, not over it: the design's line is that the Heart is
    not a UI sound, and the surest way to break that is a bright attack.
    """
    n = int(2.5 * SR)
    out = struck(n, 196.0, [
        (0.5,   0.55, 2.30),   # sub octave, the body
        (1.0,   1.00, 2.20),   # G3
        (2.013, 0.34, 1.20),   # stretched octave -- the detune is the "cast object" cue
        (2.991, 0.19, 0.70),
        (4.223, 0.085, 0.38),  # inharmonic, and gone before the ear resolves it as a pitch
        (5.667, 0.035, 0.22),
    ], "heart")

    # The strike itself: a short band of noise at the onset. Without it the tone fades *in*, and a
    # struck object never does.
    burst = highpass(white_noise(n, "heart_burst"), 200.0)
    burst = lowpass(burst, 2600.0)
    decay = math.exp(-6.907755 / (0.030 * SR))
    # The burst gets the same ~1 ms ramp the pitched partials get. Filtered noise does not start at
    # zero -- its first sample is whatever the first sample of the noise was -- so without this the
    # file opens on a step of tens of LSB, which is a click on the leading edge of the one sound in
    # the game that is supposed to arrive rather than appear. The endpoint audit in main() caught
    # exactly this; the ramp is the fix, not a loosened threshold.
    attack = max(int(0.0012 * SR), 1)
    env = 1.0
    for i in range(n):
        a = env if i >= attack else env * (i / float(attack))
        out[i] += burst[i] * a * 0.20
        env *= decay
    del burst
    return fade_tail(out, 0.12)


def sfx_restoration():
    """Something remembering its purpose; rising, small, not triumphant.

    A single voice gliding a fifth upward (A3 -> E4) over about a second, with a slow attack so it
    is heard as a thing waking rather than a thing announcing. Deliberately no octave leap, no final
    accent, no third: the art direction's Restoration-State rule is that the object becomes "active,
    coherent, warm, and slightly vulnerable", and the vulnerable part is the half that a fanfare
    would erase. It ends softer than it peaks.
    """
    n = int(2.0 * SR)
    out = [0.0] * n
    f_start, f_end = 220.0, 329.63          # A3 -> E4
    glide_n = int(1.15 * SR)
    two_pi_over_sr = (2.0 * math.pi) / SR

    # Three voices: the fundamental, a fifth above it entering late, and a faint two-octave shimmer.
    # Amplitudes fall steeply so the sum is a colour, not a chord.
    for index, (ratio, amp, enter_s, decay_from) in enumerate(
            [(1.0, 1.00, 0.00, 1.25), (1.5, 0.30, 0.42, 1.35), (4.0, 0.075, 0.62, 1.15)]):
        phase = ((_seed_for(("resto", index)) >> 8) & 0xFFFF) / 65536.0 * 2.0 * math.pi
        enter = int(enter_s * SR)
        attack = max(int(0.30 * SR), 1)
        rel_start = int(decay_from * SR)
        rel_len = max(n - rel_start, 1)
        for i in range(n):
            if i < enter:
                continue
            t = min((i / float(glide_n)), 1.0)
            hz = (f_start + (f_end - f_start) * smoothstep(t)) * ratio
            phase += two_pi_over_sr * hz
            a = smoothstep((i - enter) / float(attack))
            if i >= rel_start:
                a *= (1.0 - smoothstep((i - rel_start) / float(rel_len))) ** 1.4
            out[i] += math.sin(phase) * amp * a

    # A breath of air swelling under it and gone by the end -- matter, not magic.
    breath = lowpass(highpass(white_noise(n, "resto_air"), 900.0), 4200.0)
    for i in range(n):
        t = i / float(n)
        out[i] += breath[i] * 0.09 * (smoothstep(t / 0.45) * (1.0 - smoothstep((t - 0.45) / 0.55)))
    del breath
    return fade_tail(out, 0.15)


def sfx_threat_near():
    """Dry, close, physical; no musical pitch.

    There is not one sine in this function, and that is the point: anything with a stable pitch is
    heard as a *signal*, and a threat at the edge of the lantern light must be heard as an *object*.
    So it is three irregular grains of noise whose brightness collapses -- weight shifting on grit,
    close enough to have no reverb at all. The irregular spacing is what stops it reading as a
    machine; the total absence of tail is what stops it reading as a room.
    """
    n = int(1.5 * SR)
    out = [0.0] * n

    # (start_seconds, length_seconds, hz_start, hz_end, decay_seconds, amplitude)
    grains = [
        (0.000, 0.34, 5200.0,  420.0, 0.085, 1.00),
        (0.055, 0.26, 1800.0,  180.0, 0.150, 0.62),   # the body of the same impact, lower and later
        (0.293, 0.24, 4100.0,  520.0, 0.060, 0.47),
        (0.712, 0.30, 3400.0,  380.0, 0.075, 0.55),
        (0.760, 0.22, 1500.0,  160.0, 0.130, 0.30),
    ]
    for index, (start_s, len_s, hz0, hz1, decay_s, amp) in enumerate(grains):
        start = int(start_s * SR)
        length = min(int(len_s * SR), n - start)
        if length <= 0:
            continue
        src = highpass(white_noise(length, ("threat", index)), 60.0)
        shaped = sweeping_lowpass(src, hz0, hz1)
        del src
        decay = math.exp(-6.907755 / max(decay_s * SR, 1.0))
        attack = max(int(0.0012 * SR), 1)   # ~1 ms: sharp, but not a sample-edge click
        env = 1.0
        for i in range(length):
            a = env if i >= attack else env * (i / float(attack))
            out[start + i] += shaped[i] * amp * a
            env *= decay
        del shaped

    # One pass of highpass over the sum: removes the DC a swept lowpass on noise can accumulate,
    # and takes out the low thud that would make it sound like it happened in a bigger space.
    out = highpass(out, 45.0)
    out[0] = 0.0
    return fade_tail(out, 0.08)


# name -> (builder, loops)
SET = [
    ("AMB_Sanctuary_Day",   amb_day,            True),
    ("AMB_Sanctuary_Dusk",  amb_dusk,           True),
    ("AMB_Sanctuary_Night", amb_night,          True),
    ("AMB_Sanctuary_Dawn",  amb_dawn,           True),
    ("SFX_Heart_Warning",   sfx_heart_warning,  False),
    ("SFX_Restoration",     sfx_restoration,    False),
    ("SFX_Threat_Near",     sfx_threat_near,    False),
]


# ----------------------------------------------------------------------------------------------
# Quantisation, measurement and the failures this generator must never ship silently
# ----------------------------------------------------------------------------------------------

def quantise(sig, remove_dc):
    """Float buffer -> int16 array at TARGET_PEAK_DBFS.

    `remove_dc` is true only for the loops. Subtracting the mean from a one-shot moves its first and
    last samples off zero, which converts a clean start into a click -- the exact fault this is
    supposed to prevent. One-shots are DC-free by construction (their noise layers are highpassed
    and their envelopes end at zero) and are audited rather than corrected.
    """
    n = len(sig)
    if remove_dc:
        mean = math.fsum(sig) / n
        sig = [v - mean for v in sig]

    peak = max(max(sig), -min(sig))
    if peak <= 0.0:
        raise RuntimeError("silent buffer")
    scale = (10.0 ** (TARGET_PEAK_DBFS / 20.0)) / peak

    out = array("h", bytes(2 * n))
    for i in range(n):
        v = int(math.floor(sig[i] * scale * INT16_MAX + 0.5))
        if v > INT16_MAX:
            v = INT16_MAX
        elif v < -32768:
            v = -32768
        out[i] = v
    return out


def measure(samples):
    n = len(samples)
    peak = max(max(samples), -min(samples))
    acc = 0
    for v in samples:
        acc += v * v
    rms = math.sqrt(acc / float(n))
    dc = sum(samples) / float(n)
    return peak, rms, dc


def dbfs(linear):
    return -math.inf if linear <= 0 else 20.0 * math.log10(linear / FULL_SCALE)


def seam_audit(samples):
    """How does the wrap-around step compare with the file's own interior steps?

    Returns (wrap, max_interior, mean_interior, fraction_of_interior_steps_at_least_as_large).

    The last number is the one that carries the argument. If the loop is genuinely seamless the wrap
    is an ordinary sample-to-sample step, so a substantial share of interior steps are at least as
    big. If there is a discontinuity, that share collapses toward zero -- a seam is by definition not
    drawn from the signal's own gradient distribution. A ratio against the mean alone is not enough:
    on a near-silent bed the mean step is a fraction of an LSB and any ratio against it is noise.
    """
    n = len(samples)
    wrap = abs(samples[0] - samples[n - 1])
    biggest = 0
    total = 0
    atleast = 0
    prev = samples[0]
    for i in range(1, n):
        cur = samples[i]
        d = cur - prev
        if d < 0:
            d = -d
        if d > biggest:
            biggest = d
        total += d
        if d >= wrap:
            atleast += 1
        prev = cur
    return wrap, biggest, total / float(n - 1), atleast / float(n - 1)


# A wrap step is acceptable if it is inaudible on its own (below WRAP_ABS_LSB, ~-60 dBFS relative to
# the authored peak) OR it is an ordinary member of the interior step distribution.
WRAP_ABS_LSB = 24
WRAP_MIN_SHARE = 0.005      # at least 0.5% of interior steps must be >= the wrap step
ENDPOINT_ABS_LSB = 8        # a one-shot must start and end within this of digital silence
DC_ABS_LSB = 4


def write_wav(path, samples):
    raw = samples
    if sys.byteorder == "big":
        raw = array("h", samples)
        raw.byteswap()
    blob = raw.tobytes()
    with wave.open(path, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SR)
        handle.writeframes(blob)
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest(), os.path.getsize(path)


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: forge_sanctuary_audio.py <output-directory>")
    out_dir = os.path.abspath(sys.argv[1])
    os.makedirs(out_dir, exist_ok=True)

    print("FORGEAUD: seed=0x%X rate=%d bits=16 channels=1 target_peak=%.1f dBFS out=%s"
          % (SEED, SR, TARGET_PEAK_DBFS, out_dir))
    print("FORGEAUD: loop length %d samples (%ds) -> frequency bin resolution %.4f Hz"
          % (AMBIENT_N, AMBIENT_SECONDS, SR / float(AMBIENT_N)))
    for hz in (73.42, 110.0, 130.81, 146.83):
        print("FORGEAUD:   %.2f Hz snaps to %.4f Hz (%+.4f%%)"
              % (hz, actual_hz(hz, AMBIENT_N), 100.0 * (actual_hz(hz, AMBIENT_N) / hz - 1.0)))

    failures = []
    for name, builder, loops in SET:
        print("FORGEAUD: building %s" % name)
        samples = quantise(builder(), remove_dc=loops)
        path = os.path.join(out_dir, name + ".wav")
        digest, nbytes = write_wav(path, samples)

        n = len(samples)
        peak, rms, dc = measure(samples)
        print("FORGEAUD: %-22s %7.3fs  %8d samples  %9d B  peak=%6d (%.2f dBFS)  "
              "rms=%9.2f (%.2f dBFS)  dc=%+7.2f"
              % (name + ".wav", n / float(SR), n, nbytes, peak, dbfs(peak), rms, dbfs(rms), dc))
        print("FORGEAUD:   %-40s sha256=%s" % (name + ".wav", digest))

        if abs(dc) > DC_ABS_LSB:
            failures.append("%s DC offset is %+.2f LSB, limit %d" % (name, dc, DC_ABS_LSB))
        if peak <= 0:
            failures.append("%s is silent" % name)

        if loops:
            wrap, biggest, mean_step, share = seam_audit(samples)
            ok = wrap <= WRAP_ABS_LSB or share >= WRAP_MIN_SHARE
            print("FORGEAUD:   loop seam: wrap step=%d  interior max=%d mean=%.2f  "
                  "share of interior steps >= wrap: %.2f%%  %s"
                  % (wrap, biggest, mean_step, 100.0 * share, "OK" if ok else "<<< SEAM"))
            if not ok:
                failures.append("%s loop seam: wrap step %d is an outlier (only %.4f%% of interior "
                                "steps are as large)" % (name, wrap, 100.0 * share))
        else:
            first, last = samples[0], samples[n - 1]
            ok = abs(first) <= ENDPOINT_ABS_LSB and abs(last) <= ENDPOINT_ABS_LSB
            print("FORGEAUD:   one-shot endpoints: first=%+d last=%+d  %s"
                  % (first, last, "OK" if ok else "<<< ENDPOINT"))
            if not ok:
                failures.append("%s does not start and end at silence (first=%d last=%d)"
                                % (name, first, last))

    if failures:
        raise RuntimeError("FORGEAUD FAILED: " + "; ".join(failures))
    print("FORGEAUD: complete, %d WAV(s) in %s" % (len(SET), out_dir))


main()
